spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joostvdg/config
encrypt:
  keyStore:
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    secret: my-k34-s3cr3t
