spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joostvdg/config
        encrypt:
          enabled: false
encrypt:
  keyStore:
    location: classpath:/config-server.jks
    password: nothepassword
    alias: config-server-key
    secret: nothepassword
